name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install variant_definitions
      run: |
        git clone https://github.com/phe-genomics/variant_definitions.git

    - name: Install gumpy
      run: |
        git clone https://github.com/oxfordmmm/gumpy.git
        cd gumpy
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        python3 setup.py install --user
        cd ..

    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest tests/unit/* --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
